apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  namespace: kubeflow
spec:
  applications:
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: application/application-crds
      name: application-crds
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: application/v3
      name: application
    # Install istio in a different namespace: istio-system
    # Remove this application if istio is already installed
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: istio-1-3-1/istio-crds-1-3-1
      name: istio-crds
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: istio-1-3-1/istio-install
      name: istio-install
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: istio-1-3-1/cluster-local-gateway-1-3-1
      name: cluster-local-gateway
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: istio/istio
      name: istio
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: cert-manager/cert-manager-crds
      name: cert-manager-crds
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: cert-manager/cert-manager-kube-system-resources
      name: cert-manager-kube-system-resources
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: stacks/aws/application/cert-manager
      name: cert-manager
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: metacontroller/base
      name: metacontroller
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: stacks/aws/application/oidc-authservice
      name: oidc-authservice
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: stacks/aws/application/dex-auth
      name: dex
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: admission-webhook/bootstrap/overlays/application
      name: bootstrap
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: spark/spark-operator
      name: spark-operator
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: metadata/v3
      name: metadata
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: knative/knative-serving-crds/overlays/application
      name: knative-crds
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: knative/knative-serving-install/overlays/application
      name: knative-install
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: kfserving/kfserving-crds/overlays/application
      name: kfserving-crds
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: kfserving/kfserving-install/overlays/application
      name: kfserving-install
    # Spartakus is a separate applications so that kfctl can remove it
    # to disable usage reporting
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: common/spartakus/overlays/application
      name: spartakus
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: tensorboard/overlays/istio
      name: tensorboard
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: pipeline/api-service/overlays/application
      name: api-service
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: pipeline/persistent-agent/overlays/application
      name: persistent-agent
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: pipeline/pipelines-runner/overlays/application
      name: pipelines-runner
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: stacks/aws/application/pipelines-ui
      name: pipelines-ui
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: pipeline/pipelines-viewer/overlays/application
      name: pipelines-viewer
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: pipeline/scheduledworkflow/overlays/application
      name: scheduledworkflow
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: pipeline/pipeline-visualization-service/overlays/application
      name: pipeline-visualization-service
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: stacks/aws
      name: kubeflow-apps
  plugins:
    - kind: KfAwsPlugin
      metadata:
        name: aws
      spec:
        auth:
          basicAuth:
            password: 12341234
            username: admin@kubeflow.org
        region: us-west-2
        enablePodIamPolicy: true
        # If you don't use IAM Role for Service Account, you can still use node instance roles.
        #roles:
        #- eksctl-kubeflow-aws-nodegroup-ng-a2-NodeInstanceRole-xxxxxxx
  repos:
    - name: manifests
      uri: https://github.com/kubeflow/manifests/archive/master.tar.gz
  version: master
