apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
resources:
- ../../../../../apps/tensorboard/tensorboards-web-app/upstream/overlays/istio
- ../../../../../apps/tensorboard/tensorboard-controller/upstream/overlays/kubeflow