apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  template:
    spec:
      volumes:
        - configMap:
            name: jupyter-web-app-aws-config
          name: config-volume
