apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
configMapGenerator:
- name: jupyter-web-app-aws-config
  files:
  - spawner_ui_config.yaml
generatorOptions:
  disableNameSuffixHash: true
patchesStrategicMerge:
  - deployment.yaml