apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
commonLabels:
  app: jupyter-web-app
  kustomize.component: jupyter-web-app
bases:
- ../../base
resources:
- configMap.yaml
patchesStrategicMerge:
- deployment.yaml