apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: jupyter-web-app-
namespace: kubeflow
commonLabels:
  app: jupyter-web-app
  kustomize.component: jupyter-web-app
bases:
  - ../../base
configMapGenerator:
- name: jupyter-web-app-config
  behavior: merge
  files:
  - spawner_ui_config.yaml
generatorOptions:
  disableNameSuffixHash: true
#patchesStrategicMerge:
#  - deployment.yaml